# https://www.appveyor.com/docs/lang/go/
build: off

# fetch repository as zip archive
shallow_clone: true

clone_folder: c:\gopath\src\github.com\direnv\direnv

environment:
  GOPATH: c:\gopath
  MSYS: winsymlinks:nativestrict
  # Disable symlink-setup of GOPATH within GNUmakefile.
  DISABLE_GOPATH_SYMLINK: 1

stack: go 1.10

install:
  - mkdir C:\msys64\usr\local\bin
  - set PATH=C:\msys64\usr\bin;C:\msys64\usr\local\bin;%PATH%
  - curl -O https://storage.googleapis.com/shellcheck/shellcheck-stable.zip
  - unzip shellcheck-stable.zip shellcheck-stable.exe
  - move shellcheck-stable.exe C:\msys64\usr\local\bin\shellcheck.exe

before_test:
  - go vet ./...

test_script:
  - make test


